/* UPDATE IMG PATHS HERE
 * To change the image, just change the name, do not change the folder name, thank you.
 */
export const photoPaths = {
  LANDING_VIDEO: "/videos/landing.mp4",
  LANDING_IMAGE: "/photos/landing.webp",
  LANDING_IMAGE_2: "/photos/flagzbot.jpeg",
  WHAT_IS_K_BOT_1: "/photos/aluminium.webp",
  WHAT_IS_K_BOT_2: "/photos/actuators.webp",
  WHAT_IS_K_BOT_3: "/photos/2.webp",
  WHAT_IS_Z_BOT_1: "/photos/isaac_gym.png",
  WHAT_IS_Z_BOT_2: "/photos/zbot1.jpeg",
  WHAT_IS_Z_BOT_3: "/photos/code.png",
  GALLERY_1: "/photos/1.webp",
  GALLERY_2: "/photos/2.webp",
  GALLERY_3: "/photos/3.webp",
  GALLERY_4: "/photos/4.webp",
  GALLERY_5: "/photos/5.webp",
  GALLERY_6: "/photos/6.webp",
  ZBOT_GALLERY_1: "/photos/zbot1.jpeg",
  ZBOT_GALLERY_2: "/photos/zbotgal.jpeg",
  ZBOT_GALLERY_3: "/photos/zbotgal2.jpeg",
  ZBOT_GALLERY_4: "/photos/zbot2.jpeg",
  ZBOT_GALLERY_5: "/photos/zbotgal3.jpeg",
  ZBOT_GALLERY_6: "/photos/zbot.jpeg",
  COMMUNITY_MAIN_BIG: "/photos/team_garage.jpg",
  COMMUNITY_UPPER_RIGHT: "/photos/team_orange_bg.jpg",
  COMMUNITY_BOTTOM: "/photos/hackathon.jpeg",
  ZBOT_COMMUNITY_MAIN_BIG: "/photos/community2.jpg",
  ZBOT_COMMUNITY_BOTTOM: "/photos/community1.jpg",
  ZBOT_COMMUNITY_UPPER_RIGHT: "/photos/community3.png",
  ZBOT_TEAM: "/photos/zbotteam.png",
  ZBOT_PARTNERS_SVG_BLACK: "/photos/zbotpartnersblack.svg",
  ZBOT_PARTNERS_SVG_WHITE: "/photos/zbotpartnerswhite.svg",
  K_BOT_ACTUATOR: "/photos/kbot_actuator.png",
  K_BOT_DARK: "/photos/kbot_dark.png",
  K_BOT_TOAST_VIDEO: "/videos/toasting_bread.mp4",
  K_BOT_ACTUATOR_RENDER: "/photos/kbot_actuator_renders.png",
  K_BOT_ARM_RENDER: "/photos/kbot_arm.png",
  K_BOT_LEG_RENDER: "/photos/kbot_leg.png",
  K_BOT_TORSO_RENDER: "/photos/kbot_torso.png",
  K_BOT_KSCALE_RENDER: "/photos/kbot_kscale_labs_closeup.png",
  K_SCALE_LABS_RENDER: "/photos/kscale_labs_render.png",
};

export const photoPathAltText = {
  LANDING_VIDEO_ALT: "Video: K-Bot's landing video",
  LANDING_IMAGE_ALT: "Header",
  LANDING_IMAGE_ALT_2: "Header",
  WHAT_IS_K_BOT_1_ALT: "Photo: Close-up photo of K-Bot's aluminum chassis",
  WHAT_IS_K_BOT_2_ALT: "Photo: Close-up photo of K-Bot's 120 Nm actuators",
  WHAT_IS_K_BOT_3_ALT: "Photo: Close-up photo of K-Bot's onboard Jetson AGX",
  WHAT_IS_Z_BOT_1_ALT: "Photo: Z-Bot's advanced hardware design",
  WHAT_IS_Z_BOT_2_ALT: "Photo: Z-Bot's actuators and sensors",
  WHAT_IS_Z_BOT_3_ALT: "Photo: Z-Bot's software capabilities",
  GALLERY_1_ALT: "Gallery Image 1",
  GALLERY_2_ALT: "Gallery Image 2",
  GALLERY_3_ALT: "Gallery Image 3",
  GALLERY_4_ALT: "Gallery Image 4",
  GALLERY_5_ALT: "Gallery Image 5",
  GALLERY_6_ALT: "Gallery Image 6",
  COMMUNITY_MAIN_BIG_ALT: "Photo: k-scale team tinkering on K-Bot in the garage",
  COMMUNITY_UPPER_RIGHT_ALT: "Photo: k-scale team photo",
  COMMUNITY_BOTTOM_ALT: "Photo: k-scale labs hacakthon",
  ZBOT_COMMUNITY_MAIN_BIG_ALT: "Photo: Community members working with Zeroth Bot",
  ZBOT_COMMUNITY_BOTTOM_ALT: "Photo: Community members working with Zeroth Bot",
  ZBOT_COMMUNITY_UPPER_RIGHT_ALT: "Photo: Community collaboration",
  ZBOT_TEAM_ALT: "Photo: Zeroth Bot team members",
  ZBOT_PARTNERS_SVG_BLACK_ALT: "Photo: Our partners: k-scale labs and Grand Journey",
  ZBOT_PARTNERS_SVG_WHITE_ALT: "Photo: Our partners: k-scale labs and Grand Journey",
  K_BOT_ACTUATOR_ALT: "Photo: K-Bot's actuator",
  K_BOT_DARK_ALT: "Photo: K-Bot",
  K_BOT_TOAST_VIDEO_ALT: "Video: K-Bot toasting bread",
  K_BOT_ACTUATOR_RENDER_ALT: "Photo: K-Bot's actuator render",
  K_BOT_ARM_RENDER_ALT: "Photo: K-Bot's arm render",
  K_BOT_LEG_RENDER_ALT: "Photo: K-Bot's leg render",
  K_BOT_TORSO_RENDER_ALT: "Photo: K-Bot's torso render",
  K_BOT_KSCALE_RENDER_ALT: "Photo: K-Bot's kscale labs closeup render",
  K_SCALE_LABS_RENDER_ALT: "Photo: K-Scale Labs render",
};
